import pandas as pd
import numpy as np
from pathlib import Path

PIPE_ROOT = config.get('pipeline_root', '/home/lombelet/data-pipeline-lincoln')

MAIN = config.get('main_dir', '/groups/CaiLab')
USER = config.get('user', 'lincoln')
DATASET = config.get('dataset', '2020-08-08-takei')

RAW_DIR = Path(MAIN, 'personal', USER, 'raw', DATASET)

OUT_DIR = Path(MAIN, 'personal', 'lincoln', 'snakemake_test', DATASET)

EXP_TAB = OUT_DIR / 'exp_tab.csv'

rule find_experiment_files:
    input:
        RAW_DIR
    output:
        exp_tab=EXP_TAB
    run:
        globbed = glob_wildcards(input[0] + '/HybCycle_{hyb, \d+}/MMStack_Pos{position, \d+}.ome.tif')

        filenames = [f'{RAW_DIR}/HybCycle_{h}/MMStack_Pos{p}.ome.tif' for p, h in zip(globbed.position, globbed.hyb)]

        df = pd.DataFrame({'position': globbed.position, 'hyb': globbed.hyb, 'filename': filenames})
        df['position'] = df['position'].astype(int)
        df['hyb'] = df['hyb'].astype(int)

        df = df.set_index(['position', 'hyb']).sort_index()
        df.to_csv(output.exp_tab)

EXP_TAB_DF = pd.read_csv(EXP_TAB).set_index(['position', 'hyb'])

rule align_matlab_dapi:
    input:
       EXP_TAB,
       expand('{rawdir}/HybCycle_0/MMStack_Pos{position}.ome.tif', rawdir=RAW_DIR, position=EXP_TAB_DF.index.levels[0]),
       expand('{rawdir}/HybCycle_{hyb}/MMStack_Pos{position}.ome.tif', rawdir=RAW_DIR, position=EXP_TAB_DF.index.levels[0], hyb=EXP_TAB_DF.index.levels[1]) 
    params:
        fixed_src=str(RAW_DIR / 'HybCycle_0/MMStack_Pos{position}.ome.tif'),
        moving_src=str(RAW_DIR / 'HybCycle_{hyb}/MMStack_Pos{position}.ome.tif'),
        dest_dir=str(OUT_DIR / 'MMStack_Pos{position}/HybCycle_{hyb}/offset'),
        script_loc=str(Path(PIPE_ROOT, 'align_scripts', 'matlab_dapi.py')),
    output:
        '{params.dest_dir}.txt'
    shell:
        "python {params.script_loc} --fixed_src {params.fixed_src} --moving_src {params.moving_src} --dest_dir {params.dest_dir}"
